### ISSUE TITLE
Calling .reset() forcibly re-identifies the user causing issues with identity merge

### ISSUE THREAD

**Issue by JSanchezIO** [davide-scalzo/react-native-mixpanel#258]
## Problem
Mixpanel introduced identity merge which allows you to call `.identify(SOME_USER_ID)` and Mixpanel will then merge the profiles for the id you pass in, in this case, `SOME_USER_ID`, and the anonymous id of the user prior to identification. This scenario is currently supported by this library. However, signing out causes some issues. This is because on signout Mixpanel recommends calling `.reset()` to get a new anonymous id for the current user. In this implementation, when we call `.reset()` we immediately call `.identify()` with a newly generated id, for ease-of-use. With calling `.identify()` on `.reset()` we are implicitly merging the newly generated id with the anonymous id. This causes problems because identity merge will not work on anonymous ids that have been already merged. 

## Possible Solutions
- Allow the user to pass a boolean to `.reset()` to toggle auto-identifying the user
- Remove auto-identification from `.reset()`

## Mixpanel's Identity Merge Flow
![Mixpanel's Identity Merge Flow](https://files.readme.io/d0066f0-ID_management_identify_3-HTTP.png)

**Comment by jpalmieri** [comment]
@JSanchezIO I see you closed this issue. Were you able to resolve this, or did you maybe just close it because the library is now deprecated?

**Comment by JSanchezIO** [comment]
@jpalmieri I don't recall, the codebase that I was using this in is no longer active. I believe it was because of the PR that was merged to solve this.
